### ISSUE TITLE
Grapherl compile issue

### ISSUE THREAD

**Issue by harekumar** [processone/grapherl#4]
Hi, 

Make command is failing with the following error. Any idea what could be the reason? 

./rebar3 compile
===> Verifying dependencies...
===> Fetching eleveldb ({git,"https://github.com/basho/eleveldb.git",
                                    {branch,"master"}})
===> Failed to fetch and copy dep: {git,"https://github.com/basho/eleveldb.git",
                                   {branch,"master"}}
make: **\* [compile] Error 1

**Comment by kansi** [comment]
Hi,
try changing the following line in rebar.config
https://github.com/processone/grapherl/blob/master/grapherl/rebar.config#L7  to
{eleveldb, {git, "https://github.com/basho/eleveldb.git", **{branch, "2.0"}** }},

I have maked the change with bold in the above line i.e. change "master" to "2.0"
and compile.

Hope this helps

**Comment by harekumar** [comment]
Thanks for the help.
