### ISSUE TITLE
mod_metrics_test (Hook trigger error)

### ISSUE THREAD

**Issue by harekumar** [processone/grapherl#6]
Hi 

After enabling the above test module it is producing **_ejabberd_hooks:run1:335 {undef,[{mod_metrics_test,user_send_packet ... error_**.

As per the syntax (add hooks) things looks fine but I have no clear idea why it is happening. Any help would be appreciated.

**Comment by kansi** [comment]
@cromain any idea ?

**Comment by harekumar** [comment]
Never mind. Got it resolved. 

Looks like 15.04 expects only 3 parameter (Packet, From, To) rather than (Packet, C2SState, From, To) as per new documentation.
